# Generated by Django 3.1 on 2023-12-19 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yoga_app', '0002_auto_20231219_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_yoga', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('DD', models.CharField(blank=True, max_length=2, null=True)),
                ('MM', models.CharField(blank=True, max_length=2, null=True)),
                ('YYYY', models.CharField(blank=True, max_length=4, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_cvc', models.CharField(blank=True, max_length=3, null=True)),
                ('expiry_month', models.CharField(blank=True, max_length=2, null=True)),
                ('expiry_year', models.CharField(blank=True, max_length=4, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email_activated',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyfee',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='selected_batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=500.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yoga_app.enrollment'),
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='paid_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
