# Generated by Django 3.1 on 2023-12-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0003_auto_20231219_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
